name: Branch CI

on:
  push:
    paths-ignore:
    - 'docs/**'
    branches-ignore:
    - 'master'

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v2

    - name: Installing Catch2
      run: |
        git clone https://github.com/catchorg/Catch2.git
        pushd Catch2
        cmake -Bbuild -H. -DBUILD_TESTING=OFF
        sudo cmake --build build/ --target install
        popd

    - name: Installing CLI11
      run: |
        git clone https://github.com/CLIUtils/CLI11.git
        pushd CLI11
        cmake -Bbuild -H.
        sudo cmake --build build/ --target install
        popd

    - name: Run CMake
      run: cmake . -DENABLE_TESTS:BOOL=ON
    - name: Build
      run: make

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Installing pytest
      run: |
        pip install pytest
        pytest --version

    - name: Unit Tests
      run: make test
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: Test Results
        path: Testing/Temporary/LastTest.log
