name: Branch CI

on:
  push:
    paths-ignore:
    - 'docs/**'
    branches-ignore:
    - 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run CMake
      run: cmake .
    - name: Build
      run: make
  
  test:

    runs-on: ubuntu-latest
    needs: build
    continue-on-error: true

    steps:
    - name: Unit Tests
      run: make test
    - name: Upload test results
      uses: actions/upload-artifact@v1
      with:
        name: Test Results
        path: Testing/Temporary/LastTest.log
