name: Branch CI

on:
  push:
    paths-ignore:
    - 'docs/**'
    branches-ignore:
    - 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run CMake
      run: cmake .
    - name: Build
      run: make
    - name: test
      run: |
        ls -al
        ls -al tests
        ls -al tests/IntegrationTests
        python tests/IntegrationTests/simple_program_test.py
    - name: Unit Tests
      run: make test
    - name: PWD
      run: ls -al
    - name: Upload test results
      uses: actions/upload-artifact@v1
      with:
        name: Test Results
        path: Testing/Temporary/LastTest.log
