name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Make build directory
      run: mkdir build
    - name: Change to build directory
      run: cd build
    - name: temp
      run: |
      ls ..
      ls
      cd ..
      ls
    - name: Run CMake
      run: cmake ..
    - name: Build
      run: make
    - name: Unit Tests
      run: make test
