name: Main CI

on:
  push:
    paths-ignore:
    - 'docs/**'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run CMake
      run: cmake .
    - name: Build
      run: make
    - name: Unit Tests
      run: make test
