name: Master CI

on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'docs/**'
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    - uses: actions/checkout@v2

    - name: Installing Catch2
      run: |
        git clone https://github.com/catchorg/Catch2.git
        cd Catch2
        cmake -Bbuild -H. -DBUILD_TESTING=OFF
        sudo cmake --build build/ --target install
        cd ..
    
    - name: Run CMake
      run: cmake .
    - name: Build
      run: make
    - name: Unit Tests
      run: make test
    - name: Upload test results
      uses: actions/upload-artifact@v1
      with:
        name: Test Results
        path: Testing/Temporary/LastTest.log
