name: Master CI

on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'docs/**'
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    - uses: actions/checkout@v2

    - name: Installing Catch2
      run: |
        git clone https://github.com/catchorg/Catch2.git
        pushd Catch2
        cmake -Bbuild -H. -DBUILD_TESTING=OFF
        sudo cmake --build build/ --target install
        popd

    - name: Installing CLI11
      run: |
        git clone https://github.com/CLIUtils/CLI11.git
        pushd CLI11
        cmake -Bbuild -H. -DBUILD_TESTING=OFF
        sudo cmake --build build/ --target install
        popd

    - name: Run CMake
      run: cmake . -DBUILD_TESTING:BOOL=ON
    - name: Build
      run: make

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Installing test requirements
      run: |
        pushd ${{ github.workspace }}/tests
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        popd

    - name: Unit Tests
      run: make test
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Test Results
        path: |
          Testing/Temporary/LastTest.log
          ${{ github.workspace }}/tests/IntegrationTests/Artifacts/

  build-documentation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Test
        run: |
          pwd
          ls
          cd docs
          pwd
          ls

      - name: Run Doxygen
        uses: mattnotmitt/doxygen-action@v1.1.0
        with:
          working-directory: '${{ github.workspace }}/docs/'
          doxyfile-path: '${{ github.workspace }}/docs'